### ISSUE TITLE
No Access-Control-Allow-Origin on S3 Bucket

### ISSUE THREAD

**Issue by camb416** [Guggenheim-Helsinki/Index#1]
In my Javascript Console:

```
XMLHttpRequest cannot load https://s3-us-west-2.amazonaws.com/api.designguggenheimhelsinki.org/v1/directory.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
```

I've run into this before... S3 Needs configuring to have 

```
Access-Control-Allow-Origin *
```

Or some such thing to send crossdomain stuff.

**Comment by troyth** [comment]
Thanks @camb416 for the heads up. I added the CORS config to allow all origins for GET requests. Please let me know if it continues to break.

**Comment by camb416** [comment]
Sweet thx, had those same issues with the collections api... I'll retry and confirm fix with a close. Gracias!

**Comment by camb416** [comment]
confirmed fixed
